import type { Command, CommandContext, OutputChunk } from '../types';

const FORTUNES = [
  'The best way to predict the future is to create it.',
  'In the middle of difficulty lies opportunity.',
  'Simplicity is the ultimate sophistication.',
  "The only way to do great work is to love what you do.",
  'Life is what happens when you are busy making other plans.',
  'Be yourself; everyone else is already taken.',
  'Two things are infinite: the universe and human stupidity.',
  'The journey of a thousand miles begins with a single step.',
  "You miss 100% of the shots you don't take.",
  'Stay hungry, stay foolish.',
  "There are only 10 types of people in the world: those who understand binary and those who don't.",
  "I'm not arguing, I'm just explaining why I'm right.",
  'sudo make me a sandwich.',
  "It's not a bug — it's an undocumented feature.",
  'Chatbots are like sausages — better not to see how they are made.',
  "Why did the developer go broke? Because he used up all his cache.",
  'There is no place like ~',
  'git push --force: the only way to be sure.',
  'A clean codebase is a happy codebase.',
  'The cloud is just someone else\'s computer.',
  'In theory, theory and practice are the same. In practice, they are not.',
  'AI will not replace you. A human using AI will.',
  'Have you tried turning it off and on again?',
  'It works on my machine.',
  'This fortune was generated by a deterministic algorithm.',
];

export const fortuneCommand: Command = {
  name: 'fortune',
  help: 'Print a random, hopefully interesting, adage.',
  usage: 'fortune',
  async *run(ctx: CommandContext): AsyncIterable<OutputChunk> {
    const { isAppUnlocked } = await import('../apt/installer');
    if (!isAppUnlocked('fortune', ctx.vfs)) {
      yield "command not found: try apt install fortune\n";
      return;
    }

    const idx = Math.floor(Math.random() * FORTUNES.length);
    yield FORTUNES[idx] + '\n';
  },
};
