import type { ThemeSkin } from '../registry';

export const copilotSkin: ThemeSkin = {
  id: 'copilot',
  label: 'GitHub Copilot',
  description: 'AI pair programmer — dark with purple accents',
  palette: {
    dark: {
      'bg': '#0d1117',
      'bg-elev': '#161b22',
      'fg': '#e6edf3',
      'fg-dim': '#8b949e',
      'accent': '#8957e5',
      'accent-2': '#a371f7',
      'border': '#30363d',
      'border-glow': 'rgba(137, 87, 229, 0.3)',
      'selection': '#264f78',
      'cursor': '#e6edf3',
      'font-mono': "'JetBrains Mono', 'Fira Code', monospace",
      'font-ui': "'Inter', system-ui, sans-serif",
      'radius': '6px',
      'scanline-opacity': '0',
      'glow-strength': '0',
    },
    light: {
      'bg': '#ffffff',
      'bg-elev': '#f6f8fa',
      'fg': '#1f2328',
      'fg-dim': '#656d76',
      'accent': '#8250df',
      'accent-2': '#d93f0b',
      'border': '#d8dee4',
      'border-glow': 'rgba(130, 80, 223, 0.2)',
      'selection': '#d3d3ff',
      'cursor': '#1f2328',
      'font-mono': "'JetBrains Mono', 'Fira Code', monospace",
      'font-ui': "'Inter', system-ui, sans-serif",
      'radius': '6px',
      'scanline-opacity': '0',
      'glow-strength': '0',
    },
  },
  xtermTheme: {
    dark: {
      background: '#0d1117',
      foreground: '#e6edf3',
      cursor: '#e6edf3',
      cursorAccent: '#0d1117',
      selectionBackground: '#264f78',
      black: '#0d1117',
      red: '#ff7b72',
      green: '#3fb950',
      yellow: '#d29922',
      blue: '#58a6ff',
      magenta: '#bc8cff',
      cyan: '#39c5cf',
      white: '#e6edf3',
      brightBlack: '#484f58',
      brightRed: '#ffa198',
      brightGreen: '#56d364',
      brightYellow: '#e3b341',
      brightBlue: '#79c0ff',
      brightMagenta: '#d2a8ff',
      brightCyan: '#56d4dd',
      brightWhite: '#ffffff',
    },
    light: {
      background: '#ffffff',
      foreground: '#1f2328',
      cursor: '#1f2328',
      cursorAccent: '#ffffff',
      selectionBackground: '#d3d3ff',
      black: '#1f2328',
      red: '#d1242f',
      green: '#1a7f37',
      yellow: '#9a6700',
      blue: '#0969da',
      magenta: '#8250df',
      cyan: '#1b7c83',
      white: '#e6edf3',
      brightBlack: '#656d76',
      brightRed: '#cf222e',
      brightGreen: '#2da44e',
      brightYellow: '#bf8700',
      brightBlue: '#0550ae',
      brightMagenta: '#8250df',
      brightCyan: '#1b7c83',
      brightWhite: '#ffffff',
    },
  },
  fonts: { mono: "'JetBrains Mono', 'Fira Code', 'Cascadia Code', monospace" },
  banner(ctx) {
    const P = '\x1b[38;2;163;113;247m';  // purple
    const B = '\x1b[38;2;137;87;229m';   // dark purple
    const G = '\x1b[38;2;63;185;80m';    // green
    const D = '\x1b[2m';
    const BOLD = '\x1b[1m';
    const RST = '\x1b[0m';
    const model = ctx.model || 'gpt-4o';

    return [
      '',
      `${P}${BOLD}  ◆ GitHub Copilot${RST}`,
      `${B}  ─────────────────────────`,
      `${P}      .-------------.`,
      `${P}     ( ◉         ◉ )`,
      `${P}      |    ___    |`,
      `${P}      |   /   \\   |`,
      `${B}      \`-----------'`,
      '',
      `${G}  ✓ Workspace indexed`,
      `${G}  ✓ Suggestions active`,
      `${D}  model: ${model}`,
      `${B}  ─────────────────────────`,
      `${D}  Type to pair program · /help${RST}`,
    ].join('\r\n');
  },
  prompt: '\x1b[38;2;137;87;229m◆\x1b[0m ',
  fx: { scanlines: false, glow: false, flicker: false, curvature: false },
};
