import type { ThemeSkin } from '../registry';

export const cursorSkin: ThemeSkin = {
  id: 'cursor',
  label: 'Cursor',
  description: 'Cursor AI editor — dark slate with amber accents',
  palette: {
    dark: {
      'bg': '#0d0d0d',
      'bg-elev': '#1a1a1a',
      'fg': '#e0e0e0',
      'fg-dim': '#888888',
      'accent': '#f38518',
      'accent-2': '#ff9a33',
      'border': '#2a2a2a',
      'border-glow': 'rgba(243, 133, 24, 0.25)',
      'selection': '#2a2a2a',
      'cursor': '#f38518',
      'font-mono': "'JetBrains Mono', 'Fira Code', monospace",
      'font-ui': "'Inter', system-ui, sans-serif",
      'radius': '6px',
      'scanline-opacity': '0',
      'glow-strength': '0',
    },
    light: {
      'bg': '#fafafa',
      'bg-elev': '#f0f0f0',
      'fg': '#1a1a1a',
      'fg-dim': '#666666',
      'accent': '#d9730f',
      'accent-2': '#f38518',
      'border': '#d0d0d0',
      'border-glow': 'rgba(217, 115, 15, 0.2)',
      'selection': '#fce0c0',
      'cursor': '#1a1a1a',
      'font-mono': "'JetBrains Mono', 'Fira Code', monospace",
      'font-ui': "'Inter', system-ui, sans-serif",
      'radius': '6px',
      'scanline-opacity': '0',
      'glow-strength': '0',
    },
  },
  xtermTheme: {
    dark: {
      background: '#0d0d0d',
      foreground: '#e0e0e0',
      cursor: '#f38518',
      cursorAccent: '#0d0d0d',
      selectionBackground: '#2a2a2a',
      black: '#0d0d0d',
      red: '#e34c4c',
      green: '#5cb85c',
      yellow: '#f0ad4e',
      blue: '#4a9cf7',
      magenta: '#f38518',
      cyan: '#5bc0de',
      white: '#e0e0e0',
      brightBlack: '#555',
      brightRed: '#ff6b6b',
      brightGreen: '#6fcf6f',
      brightYellow: '#f7c35c',
      brightBlue: '#6ab0ff',
      brightMagenta: '#f39c4a',
      brightCyan: '#76d5e8',
      brightWhite: '#ffffff',
    },
    light: {
      background: '#fafafa',
      foreground: '#1a1a1a',
      cursor: '#1a1a1a',
      cursorAccent: '#ffffff',
      selectionBackground: '#fce0c0',
      black: '#1a1a1a',
      red: '#c0392b',
      green: '#27ae60',
      yellow: '#d4a017',
      blue: '#2980b9',
      magenta: '#d9730f',
      cyan: '#16a085',
      white: '#e0e0e0',
      brightBlack: '#555',
      brightRed: '#e74c3c',
      brightGreen: '#2ecc71',
      brightYellow: '#f39c12',
      brightBlue: '#3498db',
      brightMagenta: '#e67e22',
      brightCyan: '#1abc9c',
      brightWhite: '#ffffff',
    },
  },
  fonts: { mono: "'JetBrains Mono', 'Fira Code', 'Cascadia Code', monospace" },
  banner(ctx) {
    const A = '\x1b[38;2;243;133;24m';   // amber
    const D = '\x1b[38;2;217;115;15m';   // dark amber
    const DIM = '\x1b[2m';
    const BOLD = '\x1b[1m';
    const RST = '\x1b[0m';
    const model = ctx.model || 'claude-3.5-sonnet';
    const cwd = ctx.cwd || '~/project';

    return [
      '',
      `${A}${BOLD}  ❯ Cursor${RST}`,
      `${D}  ─────────────────────────`,
      `${A}  ┌─────────────────────┐`,
      `${A}  │  ${DIM}${cwd.slice(-17).padEnd(17)}${RST}${A}  │`,
      `${A}  │  ${BOLD}❯ _${RST}${A}                  │`,
      `${A}  │                     │`,
      `${D}  └─────────────────────┘`,
      '',
      `${DIM}  model  ${model}`,
      `${DIM}  context  full codebase`,
      `${D}  ─────────────────────────`,
      `${DIM}  Ask, edit, or run · /help${RST}`,
    ].join('\r\n');
  },
  prompt: '\x1b[38;2;243;133;24m❯\x1b[0m ',
  fx: { scanlines: false, glow: false, flicker: false, curvature: false },
};
