import type { ThemeSkin } from '../registry';

export const dosSkin: ThemeSkin = {
  id: 'dos',
  label: 'DOS',
  description: 'IBM PC / MS-DOS 6.22 — VGA blue, white text, batch feel',
  palette: {
    dark: {
      'bg': '#0000aa',
      'bg-elev': '#0000cc',
      'fg': '#ffffff',
      'fg-dim': '#aaaaaa',
      'accent': '#ffff55',
      'accent-2': '#ffffff',
      'border': '#0000aa',
      'border-glow': 'rgba(255,255,255,0.05)',
      'selection': '#000077',
      'cursor': '#ffffff',
      'font-mono': "'JetBrains Mono', 'Courier New', monospace",
      'font-ui': "'Inter', system-ui, sans-serif",
      'radius': '0',
      'scanline-opacity': '0',
      'glow-strength': '0',
    },
    light: {
      'bg': '#c0c0c0',
      'bg-elev': '#d4d0c8',
      'fg': '#000000',
      'fg-dim': '#444444',
      'accent': '#000080',
      'accent-2': '#000000',
      'border': '#808080',
      'border-glow': 'rgba(0,0,0,0.1)',
      'selection': '#000080',
      'cursor': '#000000',
      'font-mono': "'JetBrains Mono', 'Courier New', monospace",
      'font-ui': "'Inter', system-ui, sans-serif",
      'radius': '0',
      'scanline-opacity': '0',
      'glow-strength': '0',
    },
  },
  xtermTheme: {
    dark: {
      background: '#0000aa',
      foreground: '#ffffff',
      cursor: '#ffffff',
      cursorAccent: '#0000aa',
      selectionBackground: '#000077',
      black: '#000000',
      red: '#aa0000',
      green: '#00aa00',
      yellow: '#aa5500',
      blue: '#0000aa',
      magenta: '#aa00aa',
      cyan: '#00aaaa',
      white: '#aaaaaa',
      brightBlack: '#555555',
      brightRed: '#ff5555',
      brightGreen: '#55ff55',
      brightYellow: '#ffff55',
      brightBlue: '#5555ff',
      brightMagenta: '#ff55ff',
      brightCyan: '#55ffff',
      brightWhite: '#ffffff',
    },
    light: {
      background: '#c0c0c0',
      foreground: '#000000',
      cursor: '#000000',
      cursorAccent: '#c0c0c0',
      selectionBackground: '#000080',
      black: '#000000',
      red: '#800000',
      green: '#008000',
      yellow: '#808000',
      blue: '#000080',
      magenta: '#800080',
      cyan: '#008080',
      white: '#c0c0c0',
      brightBlack: '#808080',
      brightRed: '#ff0000',
      brightGreen: '#00ff00',
      brightYellow: '#ffff00',
      brightBlue: '#0000ff',
      brightMagenta: '#ff00ff',
      brightCyan: '#00ffff',
      brightWhite: '#ffffff',
    },
  },
  fonts: { mono: "'JetBrains Mono', 'Courier New', monospace" },
  banner(ctx) {
    const W = '\x1b[1;37m';   // bright white
    const Y = '\x1b[1;33m';   // bright yellow
    const D = '\x1b[0;37m';   // normal white/grey
    const RST = '\x1b[0m';
    const cwd = ctx.cwd || 'C:\\MIRAGE';
    const dosPath = cwd.replace(/\//g, '\\').replace(/^~/, 'C:').toUpperCase();

    return [
      '',
      `${W}    Microsoft(R) MS-DOS(R) Version 6.22`,
      `${D}    (C)Copyright Microsoft Corp 1981-1994.`,
      '',
      `${D}    C:\\>mem`,
      `${D}    655360 bytes total conventional memory`,
      `${D}    655360 bytes available to MS-DOS`,
      `${D}    580096 largest executable program size`,
      '',
      `${D}    C:\\>cd ${dosPath}`,
      '',
      `${Y}    ${dosPath}>_${RST}`,
    ].join('\r\n');
  },
  prompt: '\x1b[1;37mC:\\MIRAGE>\x1b[0m ',
};
