import type { ThemeSkin } from '../registry';

export const mythosSkin: ThemeSkin = {
  id: 'mythos',
  label: 'Mythos OS',
  description: 'Cyber-security rig — dark red, phase crab, flower sigil',
  palette: {
    dark: {
      'bg': '#0a0505',
      'bg-elev': '#140a0a',
      'fg': '#d4c0c0',
      'fg-dim': '#884444',
      'accent': '#cc2233',
      'accent-2': '#ff4455',
      'border': '#331111',
      'border-glow': 'rgba(204, 34, 51, 0.4)',
      'selection': '#2a0a0a',
      'cursor': '#cc2233',
      'font-mono': "'JetBrains Mono', 'Fira Code', monospace",
      'font-ui': "'Inter', system-ui, sans-serif",
      'radius': '2px',
      'scanline-opacity': '0.06',
      'glow-strength': '0.3',
    },
    light: {
      'bg': '#1a0a0a',
      'bg-elev': '#2a1212',
      'fg': '#e0d0d0',
      'fg-dim': '#885555',
      'accent': '#dd3344',
      'accent-2': '#ff5566',
      'border': '#442222',
      'border-glow': 'rgba(221, 51, 68, 0.3)',
      'selection': '#331515',
      'cursor': '#dd3344',
      'font-mono': "'JetBrains Mono', 'Fira Code', monospace",
      'font-ui': "'Inter', system-ui, sans-serif",
      'radius': '0',
      'scanline-opacity': '0.08',
      'glow-strength': '0.4',
    },
  },
  xtermTheme: {
    dark: {
      background: '#0a0505',
      foreground: '#d4c0c0',
      cursor: '#cc2233',
      cursorAccent: '#0a0505',
      selectionBackground: '#2a0a0a',
      black: '#0a0505',
      red: '#cc2233',
      green: '#33aa44',
      yellow: '#ccaa33',
      blue: '#4466cc',
      magenta: '#cc3366',
      cyan: '#33aaaa',
      white: '#d4c0c0',
      brightBlack: '#553333',
      brightRed: '#ff4455',
      brightGreen: '#55dd66',
      brightYellow: '#ddcc44',
      brightBlue: '#6688ee',
      brightMagenta: '#ee5588',
      brightCyan: '#55cccc',
      brightWhite: '#ffe8e8',
    },
    light: {
      background: '#1a0a0a',
      foreground: '#e0d0d0',
      cursor: '#dd3344',
      cursorAccent: '#1a0a0a',
      selectionBackground: '#331515',
      black: '#1a0a0a',
      red: '#dd3344',
      green: '#44bb55',
      yellow: '#ddbb44',
      blue: '#5577dd',
      magenta: '#dd4477',
      cyan: '#44bbbb',
      white: '#e0d0d0',
      brightBlack: '#664444',
      brightRed: '#ff5566',
      brightGreen: '#66ee77',
      brightYellow: '#eedd55',
      brightBlue: '#7788ff',
      brightMagenta: '#ff6699',
      brightCyan: '#66dddd',
      brightWhite: '#fff0f0',
    },
  },
  fonts: { mono: "'JetBrains Mono', 'Fira Code', 'Cascadia Code', monospace" },
  banner(ctx) {
    const R = '\x1b[38;2;204;34;51m';
    const G = '\x1b[38;2;51;170;68m';
    const D = '\x1b[38;2;136;68;68m';
    const B = '\x1b[38;2;255;68;85m';
    const RST = '\x1b[0m';
    const model = ctx.model || 'cyber';
    return [
      `${R}  +--[ MYTHOS OS v2.7 ]--+`,
      `${D}  +-----------------------+`,
      '',
      `${B}     -- PHASE CRAB --`,
      '',
      `${R}    ><(           )><`,
      `${R}   / \\\\   _____   / \\`,
      `${B}  |   \\_/     \\_/   |`,
      `${R}   \\   |  . .  |   /`,
      `${R}    \`--|_______|--\'`,
      '',
      `${G}    * + * + * + * + *`,
      '',
      `${D}  ==========================`,
      `${R}  mythos@${model}  ${D}|${RST}  ${G}${ctx.cwd}`,
      `${D}  ==========================`,
      '',
      `${R}  * AUDIT MODE ACTIVE *${RST}`,
    ].join('\r\n');
  },
  prompt: '\x1b[38;2;204;34;51mroot\x1b[38;2;136;68;68m@\x1b[38;2;204;34;51mmythos\x1b[0m:\x1b[38;2;51;170;68m~\x1b[0m# ',
  fx: { scanlines: true, glow: true, flicker: false, curvature: false },
};
