import type { ThemeSkin } from '../registry';

export const windsurfSkin: ThemeSkin = {
  id: 'windsurf',
  label: 'Windsurf',
  description: 'Agentic IDE — deep ocean with neon cyan/blue',
  palette: {
    dark: {
      'bg': '#0b1219',
      'bg-elev': '#141e2a',
      'fg': '#d4dfe8',
      'fg-dim': '#6e8ba3',
      'accent': '#00d4aa',
      'accent-2': '#00bcd4',
      'border': '#1e3347',
      'border-glow': 'rgba(0, 212, 170, 0.3)',
      'selection': '#1a2d3d',
      'cursor': '#00d4aa',
      'font-mono': "'JetBrains Mono', 'Fira Code', monospace",
      'font-ui': "'Inter', system-ui, sans-serif",
      'radius': '8px',
      'scanline-opacity': '0',
      'glow-strength': '0.15',
    },
    light: {
      'bg': '#f0f6fc',
      'bg-elev': '#e4eef7',
      'fg': '#0b1219',
      'fg-dim': '#4a6a7f',
      'accent': '#009977',
      'accent-2': '#0088aa',
      'border': '#b8ccda',
      'border-glow': 'rgba(0, 153, 119, 0.2)',
      'selection': '#cce0f0',
      'cursor': '#0b1219',
      'font-mono': "'JetBrains Mono', 'Fira Code', monospace",
      'font-ui': "'Inter', system-ui, sans-serif",
      'radius': '8px',
      'scanline-opacity': '0',
      'glow-strength': '0',
    },
  },
  xtermTheme: {
    dark: {
      background: '#0b1219',
      foreground: '#d4dfe8',
      cursor: '#00d4aa',
      cursorAccent: '#0b1219',
      selectionBackground: '#1a2d3d',
      black: '#0b1219',
      red: '#e06c75',
      green: '#00d4aa',
      yellow: '#e5c07b',
      blue: '#61afef',
      magenta: '#c678dd',
      cyan: '#00bcd4',
      white: '#d4dfe8',
      brightBlack: '#4a6a7f',
      brightRed: '#ff7a85',
      brightGreen: '#33e6bf',
      brightYellow: '#f0cf8a',
      brightBlue: '#7ac0ff',
      brightMagenta: '#d48aed',
      brightCyan: '#4ad4e8',
      brightWhite: '#ffffff',
    },
    light: {
      background: '#f0f6fc',
      foreground: '#0b1219',
      cursor: '#0b1219',
      cursorAccent: '#ffffff',
      selectionBackground: '#cce0f0',
      black: '#0b1219',
      red: '#cc3344',
      green: '#009977',
      yellow: '#997700',
      blue: '#2266aa',
      magenta: '#8844aa',
      cyan: '#0088aa',
      white: '#d4dfe8',
      brightBlack: '#4a6a7f',
      brightRed: '#e06c75',
      brightGreen: '#00d4aa',
      brightYellow: '#e5c07b',
      brightBlue: '#61afef',
      brightMagenta: '#c678dd',
      brightCyan: '#00bcd4',
      brightWhite: '#ffffff',
    },
  },
  fonts: { mono: "'JetBrains Mono', 'Fira Code', 'Cascadia Code', monospace" },
  banner(ctx) {
    const T = '\x1b[38;2;0;212;170m';    // teal
    const C = '\x1b[38;2;0;188;212m';    // cyan
    const D = '\x1b[38;2;0;153;170m';    // dark teal
    const DIM = '\x1b[2m';
    const BOLD = '\x1b[1m';
    const RST = '\x1b[0m';
    const model = ctx.model || 'claude-3.5-sonnet';

    return [
      '',
      `${T}${BOLD}  🌊 Windsurf${RST}`,
      `${D}  ─────────────────────────`,
      `${T}           /`,
      `${T}          /|`,
      `${C}         / |`,
      `${C}        /  |`,
      `${D}  ~~~~~(   )~~~~~~~~~~~~~~~~`,
      '',
      `${T}  ✦ Cascade agent active`,
      `${DIM}  model  ${model}`,
      `${DIM}  flow   deep codebase`,
      `${D}  ─────────────────────────`,
      `${DIM}  Surf the code · /help${RST}`,
    ].join('\r\n');
  },
  prompt: '\x1b[38;2;0;212;170m🌊\x1b[0m ',
  fx: { scanlines: false, glow: true, flicker: false, curvature: false },
};
