// One-shot generator: writes src/agents/ascii.ts with exact figlet output.
const figlet = require('figlet');
const fs = require('fs');
const path = require('path');

function art(text, font) {
  return figlet
    .textSync(text, { font })
    .split('\n')
    .map((l) => l.replace(/\s+$/, ''))
    .filter((l, i, arr) => !(l === '' && (i === 0 || i === arr.length - 1)));
}

const out = `/* AUTO-GENERATED by scripts/gen-ascii.cjs — do not edit by hand. */

export const ANTIGRAVITY_ART: string[] = ${JSON.stringify(art('ANTIGRAVITY', 'Small'), null, 0)};

export const GEMINI_ART: string[] = ${JSON.stringify(art('GEMINI', 'ANSI Shadow'), null, 0)};

export const OPENCODE_ART: string[] = ${JSON.stringify(art('opencode', 'Small'), null, 0)};

export const MYTHOS_ART: string[] = ${JSON.stringify(art('MYTHOS', 'Small'), null, 0)};
`;

fs.writeFileSync(path.join(__dirname, '..', 'src', 'agents', 'ascii.ts'), out);
console.log('ascii.ts written');
